// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvsNVwzKZ_MV0jMeCucCCJiyHJXQOIVU4',
    appId: '1:448656608748:web:c673ac09d873779a8344c9',
    messagingSenderId: '448656608748',
    projectId: 'todo-1de71',
    authDomain: 'todo-1de71.firebaseapp.com',
    storageBucket: 'todo-1de71.appspot.com',
    measurementId: 'G-2FDE1C8N4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB910pAzSZndAM29xfb4JA7yfU2yUq30kI',
    appId: '1:448656608748:android:709384b9c361647e8344c9',
    messagingSenderId: '448656608748',
    projectId: 'todo-1de71',
    storageBucket: 'todo-1de71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhW3K0iMJOMtei_jIfU2jru9b8H4ENaFk',
    appId: '1:448656608748:ios:5ac20f36d67c91ed8344c9',
    messagingSenderId: '448656608748',
    projectId: 'todo-1de71',
    storageBucket: 'todo-1de71.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhW3K0iMJOMtei_jIfU2jru9b8H4ENaFk',
    appId: '1:448656608748:ios:5ac20f36d67c91ed8344c9',
    messagingSenderId: '448656608748',
    projectId: 'todo-1de71',
    storageBucket: 'todo-1de71.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvsNVwzKZ_MV0jMeCucCCJiyHJXQOIVU4',
    appId: '1:448656608748:web:e1ba03fb2710a0098344c9',
    messagingSenderId: '448656608748',
    projectId: 'todo-1de71',
    authDomain: 'todo-1de71.firebaseapp.com',
    storageBucket: 'todo-1de71.appspot.com',
    measurementId: 'G-6JV7CV0VY3',
  );
}
